src/home/urls.py
from django.conf.urls import url
from .views import Home, SignUp, Logout, Redir

# New in Django 2.0
# the app_name attribute needs to be set to facilitate include in root urls.py
app_name = 'home'

urlpatterns = [url(r'^login/$',Home.as_view(),name='home'),
               url(r'^$',Redir.as_view(),name='redirect'),
               url(r'^signup/$',SignUp.as_view(),name='signup'),
               url(r'^logout/$',Logout.as_view(),name='logout'),
    ]

src/rolls/urls.py
from django.conf.urls import url
from .views import Home, Upload, Manage, like

# New in Django 2.0
# the app_name attribute needs to be set to facilitate include in root urls.py
app_name = 'rolls'

urlpatterns = [url(r'^(/?order=(?P<order>[a-zA-Z\-]+))?$',Home.as_view(),name='home'), 
               url(r'^upload/$',Upload.as_view(),name='upload'),
               url(r'^manage/$',Manage.as_view(),name='manage'),
               url(r'^like/$',like,name='like')
]

src/home/models.py
from django.db import models

# Create your models here.

src/home/forms.py
from django import forms
from django.utils.timezone import now
from users.models import UserAuth



class UserLoginForm(forms.Form):
    """
    Purpose: Facilitate login
	Model Linked: None
	Authentication backend handles appropriate model.
    """
    email = forms.EmailField(max_length=64,label="Email Address")
    password = forms.CharField(max_length=None,widget=forms.widgets.PasswordInput)

src/home/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.contrib.auth.hashers import make_password

from .forms import UserLoginForm
from users.models import UserAuth
# Create your views here.

class Redir(TemplateView):
    def get(self, request, *args, **kwargs):
        return redirect('home:home')

class Home(TemplateView):
    '''
    Contains a login form
    '''
    template_name = 'home/index.html'

    def post(self,request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            try:
                email = UserAuth.objects.get(email=form.cleaned_data['email'])
                password = form.cleaned_data['password']
                user = authenticate(username=email,password=password)
                if user is None:
                    raise ValidationError(message='Validation Failed')
            except (ObjectDoesNotExist,ValidationError):
                messages.add_message(request,messages.ERROR,'Username Or Password Does Not Match')
                return redirect('home:home')
            login(request,user)
            messages.add_message(request,messages.SUCCESS,'You Have Been Logged In!')
            return redirect('rolls:home')
        else:
            messages.add_message(request,messages.ERROR,'Invalid Form')
            return redirect('home:home')

class SignUp(TemplateView):
    template_name = 'home/signup.html'

    def post(self,request):
        email = request.POST['email']
        pw1 = request.POST['password1']
        pw2 = request.POST['password2']
        if pw1 != pw2:
            messages.add_message(request,messages.ERROR,'Passwords Do Not Match!')
            return redirect('home:signup')
        else:
            try:
                pw = make_password(pw1)
                user = UserAuth.objects.create(email=email,password=pw)
            except:
                messages.add_message(request,messages.ERROR,'User Already Exists')
                return redirect('home:signup')
            messages.add_message(request,messages.SUCCESS,
		    'Your Account Has Been Created! Go Ahead and Log in!!')
            return redirect('home:home')


class Logout(TemplateView):

    def get(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request,messages.SUCCESS,'You Have Been Logged Out!')
        return redirect('home:home')

src/home/templates/master_template.html
<html lang="en">
<head>
    <title>J&J's Wedding Roll</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A Wedding Roll">
    <meta name="author" content="Ronit Rudra">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <style type="text/css">
        html, body {
            height: 100%;
            background-color:whitesmoke;
        }
    </style>
</head>
    <body class="body">
        {% load static %}

        <div class="container-fluid">
            {% block nav %}
            <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:home' %}">J&J's Wedding Album</a>

                <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            {% if user.is_authenticated %}
                            <a class="nav-link" id="id_upload" href="{% url 'rolls:upload' %}">Upload <span class="sr-only">(current)</span></a>
                            {% endif %}
                        </li>

                    </ul>
                    <ul class="form-inline my-2 my-lg-0">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link active" id="id_logout" href="{% url 'home:logout' %}" style="color:black"><strong>Logout</strong></a>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            {% endblock %}


            {% block message%}
            {% if messages %}
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <ul class="messages">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </ul>
            </div>
            {% endfor %}
            {% endif %}
            {% endblock %}

            <div align="center">
                {% block content %}
                {% endblock %}
            </div>
            <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>-->
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            {% block scripts %}
            {% endblock %}
        </div>
    </body>
</html>