src/home/urls.py
from django.conf.urls import url
from .views import Home, SignUp, Logout, Redir

# New in Django 2.0
# the app_name attribute needs to be set to facilitate include in root urls.py
app_name = 'home'

urlpatterns = [url(r'^login/$',Home.as_view(),name='home'),
               url(r'^$',Redir.as_view(),name='redirect'),
               url(r'^signup/$',SignUp.as_view(),name='signup'),
               url(r'^logout/$',Logout.as_view(),name='logout'),
    ]

src/rolls/urls.py
from django.conf.urls import url
from .views import Home, Upload, Manage, like

# New in Django 2.0
# the app_name attribute needs to be set to facilitate include in root urls.py
app_name = 'rolls'

urlpatterns = [url(r'^(/?order=(?P<order>[a-zA-Z\-]+))?$',Home.as_view(),name='home'), 
               url(r'^upload/$',Upload.as_view(),name='upload'),
               url(r'^manage/$',Manage.as_view(),name='manage'),
               url(r'^like/$',like,name='like')
]

src/home/models.py
from django.db import models

# Create your models here.

src/rolls/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from users.models import UserAuth
# Create your models here.


class Uploads(models.Model):
    photo_url = models.ImageField(upload_to='uploaded_files', verbose_name='uploads')
    date_posted = models.DateTimeField(default=now)
    uploader = models.ForeignKey(UserAuth, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)
    description = models.TextField(default='')
    slug = models.SlugField(max_length=255)
    likes = models.ManyToManyField(UserAuth,related_name='likes')
    total = models.IntegerField(default=0)

    class Meta:
        verbose_name = _('upload')
        verbose_name_plural = _('uploads')

    def __str__(self):
        return str(self.uploader.email)

    @property
    def total_likes(self):
        return self.likes.count()

    def save(self,*args,**kwargs):
        self.slug=slugify('{}-{}-{}'.format(str(self.uploader),
                                            str(self.date_posted),
                                            self.description))
        super(Uploads,self).save(*args,**kwargs)

src/home/forms.py
from django import forms
from django.utils.timezone import now
from users.models import UserAuth



class UserLoginForm(forms.Form):
    """
    Purpose: Facilitate login
	Model Linked: None
	Authentication backend handles appropriate model.
    """
    email = forms.EmailField(max_length=64,label="Email Address")
    password = forms.CharField(max_length=None,widget=forms.widgets.PasswordInput)

src/rolls/forms.py
from django import forms
from .models import Uploads
from users.models import UserAuth

class UploadForm(forms.ModelForm):
    class Meta:
        model = Uploads
        fields = ('photo_url','description')
        exclude = ('uploader','date_posted','is_approved')

    def __init__(self, *args, **kwargs):
        super(UploadForm,self).__init__(*args,**kwargs)
        f = self.fields.get('user_permissions',None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

src/home/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.contrib.auth.hashers import make_password

from .forms import UserLoginForm
from users.models import UserAuth
# Create your views here.

class Redir(TemplateView):
    def get(self, request, *args, **kwargs):
        return redirect('home:home')

class Home(TemplateView):
    '''
    Contains a login form
    '''
    template_name = 'home/index.html'

    def post(self,request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            try:
                email = UserAuth.objects.get(email=form.cleaned_data['email'])
                password = form.cleaned_data['password']
                user = authenticate(username=email,password=password)
                if user is None:
                    raise ValidationError(message='Validation Failed')
            except (ObjectDoesNotExist,ValidationError):
                messages.add_message(request,messages.ERROR,'Username Or Password Does Not Match')
                return redirect('home:home')
            login(request,user)
            messages.add_message(request,messages.SUCCESS,'You Have Been Logged In!')
            return redirect('rolls:home')
        else:
            messages.add_message(request,messages.ERROR,'Invalid Form')
            return redirect('home:home')

class SignUp(TemplateView):
    template_name = 'home/signup.html'

    def post(self,request):
        email = request.POST['email']
        pw1 = request.POST['password1']
        pw2 = request.POST['password2']
        if pw1 != pw2:
            messages.add_message(request,messages.ERROR,'Passwords Do Not Match!')
            return redirect('home:signup')
        else:
            try:
                pw = make_password(pw1)
                user = UserAuth.objects.create(email=email,password=pw)
            except:
                messages.add_message(request,messages.ERROR,'User Already Exists')
                return redirect('home:signup')
            messages.add_message(request,messages.SUCCESS,
		    'Your Account Has Been Created! Go Ahead and Log in!!')
            return redirect('home:home')


class Logout(TemplateView):

    def get(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request,messages.SUCCESS,'You Have Been Logged Out!')
        return redirect('home:home')

src/rolls/views.py
import json

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView, ListView
from .forms import UploadForm
from .models import Uploads
from users.models import UserAuth
# Create your views here.

class Home(ListView):
    template_name='rolls/home.html'
    model = Uploads

    def dispatch(self, request, *args, **kwargs):
        if self.kwargs['order'] not in [None,'date-desc',
                                        'date-asc','likes-desc',
                                        'likes-asc']:
            return redirect('rolls:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        query_set = Uploads.objects.filter(is_approved=True)
        query = self.kwargs['order']
        if query is not None:
            if query == 'date-desc':
                return query_set.order_by('-date_posted') 
            elif query == 'date-asc':
                return query_set.order_by('date_posted') 
            elif query == 'likes-desc':
                return query_set.order_by('-total') 
            elif query == 'likes-asc':  
                return query_set.order_by('total')
        else:
            return query_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_pending'] = Uploads.objects.filter(is_approved=False).count()
        return context



class Upload(TemplateView):
    template_name = 'rolls/upload.html'

    def get(self,request, *args, **kwargs):
        form = UploadForm()
        return render(request,self.template_name,{'form':form})

    def post(self,request, *args, **kwargs):
        form=UploadForm(request.POST,request.FILES)
        if form.is_valid():
            # Poster ID is required, hence assign through request
            obj = form.save(commit=False)
            obj.uploader = request.user
            if request.user.is_owner:
                obj.is_approved=True
                messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your Photo Has Been Uploaded!!')
            else:
                messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your Photo Has Been Uploaded But Will NOT Be Visible Untill Jane Or Joe Approve It.')
            obj.save()

            return redirect('rolls:home')
        else:
            messages.add_message(request,messages.ERROR,'File is NOT an Image')
            return redirect('rolls:upload')
      
class Manage(ListView):
    template_name = 'rolls/manage.html'
    model = Uploads

    def get(self, request, *args, **kwargs):
        if request.user.is_owner:
            return super().get(request, *args, **kwargs)
        else:
            return redirect('rolls:home')

    def get_queryset(self):
        return Uploads.objects.filter(is_approved=False).order_by('-date_posted')

    def post(self,request, *args, **kwargs):
        if request.user.is_owner:
            for key,val in request.POST.items():
                if key == 'csrfmiddlewaretoken':
                    pass
                else:
                    obj = Uploads.objects.get(id=val)
                    print(obj)
                    obj.is_approved = True
                    obj.save()
            return redirect('rolls:home')
        else:
            return redirect('home:home')

@require_POST
def like(request):
    """
    Not A View that returns an HTML Page.
    Handles AJAX calls from the Like Button.
    """
    if request.method == 'POST':
        user = request.user
        slug = request.POST.get('slug',None)
        photo = get_object_or_404(Uploads,slug=slug)

        if photo.likes.filter(id=user.id).exists():
            photo.likes.remove(user)
            photo.total -=1
            photo.save()
        else:
            photo.likes.add(user)
            photo.total+=1
            photo.save()

    context = {'likes_count':photo.total_likes}
    return HttpResponse(json.dumps(context),content_type='applications/json')

src/rolls/templates/rolls/home.html
{% extends 'master_template.html' %}
{% block content %}
<h1 class="my-4 text-center text-lg-left">Wedding Gallery</h1>
    {% if user.is_owner %}
<a align="center" class="btn btn-info" href="{% url 'rolls:manage' %}" id="id_manage">Manage Pending Requests ({{num_pending}})</a>
    {% endif %}
{% if uploads_list|length > 0 %}
<div align="right"><a class="btn btn-outline-dark" style="pointer-events:none;cursor:default">SORT:</a>
    <div class="btn-group">
        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Date</button>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="order=date-asc">Ascending</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="order=date-desc">Descending</a>
        </div>
    </div>
    <div class="btn-group">
        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Likes</button>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="order=likes-asc">Ascending</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="order=likes-desc">Descending</a>
        </div>
    </div>
</div>
<div class="row text-center text-sm-left">
    {% for upload in uploads_list %}

    <div class="col-lg-3 col-md-4 col-xs-6">
        <i>{{upload.date_posted|date}}</i> : <strong>{{upload.description|upper}}</strong>
        <a href="{{upload.photo_url.url}}">
            <img class="img-fluid img-thumbnail" src="{{upload.photo_url.url}}">
        </a>
        <input type="button" class="like btn btn-primary" id="{{upload.slug}}" name="{{ upload.slug }}" value="like {{upload.total_likes}}" />
        by <i>{{upload.uploader}}</i>
    </div>
    {% endfor %}
</div>
    {% else %}
<h1>Oops! No Photos Have Been Uploaded Yet!!</h1>
    {% endif %}

{% endblock %}

{% block scripts %}
<script>
    $('.like').click(function () {
        var id = $(this).attr("id");
            $.ajax({
                type: "POST",
                url: "{% url 'rolls:like' %}",
                data: { 'slug': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (response) {
                    var elem = document.getElementById(id);
                    elem.value = 'Like ' + response.likes_count;
                    },
                    error: function(rs, e) {
                           alert(rs.responseText);
                    }
              });
        })
</script>
{% endblock %}

src/rolls/templates/rolls/manage.html
{% extends 'master_template.html' %}
{% block content %}
<h1 class="my-4 text-center text-lg-left">Choose Photos That Should Be Visible</h1>
<br />
    {% if uploads_list|length > 0 %}
<form method="post">
    <button type="submit" id="id_approve" class="btn btn-info" align="center">Approve</button>
    <br />
    {% csrf_token %}
    <div class="row text-center text-sm-left">
        {% for upload in uploads_list %}
        <div class="col-lg-3 col-md-4 col-xs-6">
            <input type="checkbox" name="{{upload}}"
                   id="id_{{upload}}"
                   value="{{upload.id}}" /> <strong>{{upload.description}}</strong>
            <a href="{{upload.photo_url.url}}">
                <img src="{{upload.photo_url.url}}" class="img-fluid img-thumbnail" />
            </a>
                <p>{{upload.date_posted}} by <i>{{upload}}</i></p>
        </div>
        {% endfor %}
        <br />
    </div>
</form>

    {% else %}
<h1>No Pending Requests Yet!!</h1>
    {% endif %}
{% endblock %}

src/rolls/templates/rolls/upload.html
{% extends 'master_template.html' %}

{% block content %}
<div class="w-25 p-3">
    <form method="post" enctype="multipart/form-data" class="form-signin">
        {% csrf_token %}
        <!-- <input type="file" name="upload_photo" id="id_upload_photo" /></p> -->
        <label for="id_photo_url">UPLOAD:</label>
        <input type="file" name="photo_url" required id="id_photo_url" class="form-control" />
        <br />
        <label for="id_description">DESCRIPTION:</label>
        <textarea name="description" cols="40" rows="5" required id="id_description" class="form-control"></textarea>
        <br />
        <button type="submit" id="id_submit" class="btn btn-primary">Upload</button>
    </form>
</div>
    {% endblock %}